export const HANDLE_CHANGE="HANDLE_CHANGE"

export const HANDLE_CHECK="HANDLE_CHECK"


export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

export const UPLOAD_IMAGE="UPLOAD_IMAGE"

export const GET_FEATURED="GET_FEATURED"


export const getSingleProperty="getSingleProperty"

export const GET_ALL_PROPERTY="GET_ALL_PROPERTY"

export const GET_ALL_PROPERTY_WITH_OUT_FILTERS="GET_ALL_PROPERTY_WITH_OUT_FILTERS"


export const CLEAR_FILTERS="CLEAR_FILTERS"

export const CREATE_ORDER="CREATE_ORDER"
export const CREATE_ORDER_ERROR="CREATE_ORDER_ERROR"

export const GET_CURRENT_USER_ORDERS="GET_CURRENT_USER_ORDERS"

export const NEWS_LETTER_SUCCESS="NEWS_LETTER_SUCCESS"
export const NEWS_LETTER_ERROR="NEWS_LETTER_ERROR"


export const UPDATE_PASSSOWRD_SUCCESS="UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSSOWRD_ERROR="UPDATE_PASSWORD_ERROR"

export const UPLOAD_IMAGE_USER="UPLOAD_IMAGE_USER"

export const GET_STRIPE="GET_STRIPE"
export const SUCCESS_OR_FAILURE_ACTIONS="SUCCESS_OR_FAILURE_ACTIONS"


export const FORGET_PASSWORD_SUCCESS="FORGET_PASSWORD_SUCCESS"
export const FORGET_PASSWORD_BEGIN="FORGET_PASSWORD_BEGIN"
export const FORGET_PASSWORD_ERROR="FORGET_PASSWORD_ERROR"


export const RESET_PASSWORD_SUCCESS="FORGET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_ERROR="FORGET_PASSWORD_ERROR"

export const STRIP_LOADING_BEGIN="STRIPE_LOADING_BEGIN"
export const STRIP_LOADING_END="STRIPE_LOADING_END"